//! Acceptance test for AC7 (SHOULD) — generated by `autobuilder scaffold`.
//!
//! Project: agorabus (cli)
//! AC description: JSON line protocol is robust to malformed input: a client sending non-JSON or a JSON object missing `op` receives an `{"ok":false,"error":...}` reply and the connection is closed; other clients are unaffected.
//! Test predicate: tests/acceptance_ac7.rs
//!
//! Ownership split: this //! header block (AC metadata) is
//! read-only — to change an AC, file
//! agent/intent_card_amendment_request.json and re-scaffold. The
//! `fn acceptance_ac7` body BELOW is owned by the edit-agent: replace
//! the panic stub with a real assertion that verifies the AC
//! description above.

#![allow(clippy::unwrap_used, clippy::expect_used, clippy::doc_markdown)]

#[test]
fn acceptance_ac7() {
    // edit-agent: replace this stub with a real assertion. The
    // panic keeps the test failing until you do, so the loop
    // sees a real Stage 3 signal.
    panic!("AC AC7 not yet implemented — see file header");
}
